# Generated by Django 4.2.7 on 2023-11-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
    ]
